@url_dev=http://localhost:3056/v1/api/

### signup
POST {{url_dev}}shop/signup
Content-Type: application/json
x-api-key: b17aa3dcd597feb4fecf11be74ab678e90109127e7a2e9373369a159e7b17f0a02cdefcf20262f76d36113e7b20e47e660e83c5031e4bdcdea705ca85c62cb5c

{
    "name": "Shop Reina",
    "email": "thaonguyengdev@gmail.com",
    "password": "Matkhausieumanh123"
}